### ISSUE TITLE
Erro ao realizar deploy.

### ISSUE THREAD

**Issue by leandroramos** [fflch/solicita-site#25]
Por favor, melhorar instruções de deploy no README
Depois do composer install, quando ele vai fazer o postAutoLoadDump, ele dá o erro 
```php
ReflectionException  : Class Uspdev\SenhaunicaSocialite\SenhaunicaExtendSocialite does not exist
```

**Comment by girol** [comment]
Mexi tudo @leandroramos , foi mal :stuck_out_tongue_closed_eyes:

**Comment by thiagogomesverissimo** [comment]
Vou arrumar sim o readme. Valeu pela issue.

**Comment by thiagogomesverissimo** [comment]
Vou mandar o screenshot desse sistema em funcionamento. Como ele está muito acoplado ao aegir, a documentação precisa ser melhor elaborada. Mas posso mostrar ele em funcionamento até terminarmos de escrever a doc
![Captura de tela em 2019-05-21 11-09-49](https://user-images.githubusercontent.com/908508/58103255-100d8b00-7bb9-11e9-932d-34c1dcc76f40.png)
![Captura de tela em 2019-05-21 11-09-58](https://user-images.githubusercontent.com/908508/58103262-126fe500-7bb9-11e9-9389-edb4473d1ad8.png)
